# Generated by Django 5.1.6 on 2025-02-21 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartZamovApp', '0002_product_image2_product_image3_product_image4_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image2',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
