# Generated by Django 5.1.6 on 2025-02-22 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartZamovApp', '0004_alter_product_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='adress',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
