# Generated by Django 5.1.6 on 2025-02-22 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartZamovApp', '0005_customuser_adress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
