# Generated by Django 5.1.6 on 2025-02-24 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartZamovApp', '0007_alter_order_status_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='text_de',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='text_ru',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='text_uk',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
