# Generated by Django 5.1.6 on 2025-02-25 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartZamovApp', '0010_customuser_patronymic'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(blank=True, choices=[('UkrPost', 'UkrPost pay on delivery'), ('NovaPost', 'NovaPost pay on delivery'), ('Сourier', 'Сourier pay on delivery (Only for Dnipro and Berlin)')], max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='order_adress',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('CashOnDelivery', 'In post cash on delivery'), ('OnCard', 'On cart'), ('crypto', 'On crypto')], max_length=40, null=True),
        ),
    ]
