# Generated by Django 5.1.6 on 2025-02-26 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartZamovApp', '0011_order_delivery_method_order_is_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='recipient_name',
            field=models.CharField(default=1, max_length=80),
            preserve_default=False,
        ),
    ]
