# Generated by Django 5.1.6 on 2025-02-26 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartZamovApp', '0013_alter_order_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(blank=True, choices=[('UkrPost', 'UkrPost pay on delivery'), ('NovaPost', 'NovaPost pay on delivery'), ('Courier', 'Courier pay on delivery (Only for Dnipro and Berlin)')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='recipient_name',
            field=models.CharField(default=1, max_length=80),
            preserve_default=False,
        ),
    ]
