# Generated by Django 5.1.6 on 2025-02-26 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SmartZamovApp', '0015_alter_order_recipient_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='price',
        ),
    ]
