# Generated by Django 5.1.6 on 2025-02-26 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartZamovApp', '0016_remove_order_total_remove_orderitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(blank=True, choices=[('UkrPost', 'UkrPost pay on delivery'), ('NovaPost', 'NovaPost pay on delivery'), ('Сourier', 'Сourier pay on delivery (Only for Dnipro and Berlin)')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='recipient_name',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
