# Generated by Django 5.1.6 on 2025-03-01 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartZamovApp', '0017_alter_order_delivery_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='viewed_products',
            field=models.ManyToManyField(blank=True, related_name='viewed_products', to='SmartZamovApp.product'),
        ),
    ]
