# Generated by Django 5.1.6 on 2025-03-02 12:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartZamovApp', '0018_customuser_viewed_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='viewed_products',
        ),
        migrations.CreateModel(
            name='ViewProd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewed_by_users', to='SmartZamovApp.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewed_products', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
