# Generated by Django 5.1.6 on 2025-03-20 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartZamovApp', '0019_remove_customuser_viewed_products_viewprod'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='tg_id',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
