# Generated by Django 5.1.6 on 2025-03-21 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartZamovApp', '0021_message_text_en_product_description_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='text_uk',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description_uk',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name_uk',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_uk',
        ),
        migrations.RemoveField(
            model_name='product_category',
            name='name_uk',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('On_cart', 'В кошику'), ('pending', 'Pending'), ('completed', 'Completed'), ('active', 'Active'), ('shipped', 'Shipped'), ('canceled', 'Canceled')], default='pending', max_length=40),
        ),
    ]
