# Generated by Django 5.1.6 on 2025-03-21 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartZamovApp', '0022_remove_message_text_uk_remove_product_description_uk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('On_cart', 'В кошику'), ('pending', 'Pending'), ('completed', 'Completed'), ('active', 'Active'), ('shipped', 'Shipped'), ('canceled', 'Canceled')], default='On_cart', max_length=40),
        ),
    ]
