# Generated by Django 5.1.6 on 2025-03-21 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartZamovApp', '0023_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('On cart', 'В кошику'), ('pending', 'Pending'), ('completed', 'Completed'), ('active', 'Active'), ('shipped', 'Shipped'), ('canceled', 'Canceled')], default='On_cart', max_length=40),
        ),
    ]
