# Generated by Django 5.1.6 on 2025-03-21 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartZamovApp', '0024_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(blank=True, choices=[('Почта России', 'Почта России'), ('СДЭК', 'СДЭК'), ('Сourier (Only for Moscow and Berlin)', 'Сourier')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('In post cash on delivery', 'Cash on delivery'), ('On card', 'On card'), ('On crypto', 'Crypto')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('В кошику', 'On cart'), ('Pending', 'pending'), ('Completed', 'completed'), ('Active', 'active'), ('Shipped', 'shipped'), ('Canceled', 'canceled')], default='On_cart', max_length=40),
        ),
    ]
