# Generated by Django 5.1.6 on 2025-03-21 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartZamovApp', '0025_alter_order_delivery_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(blank=True, choices=[('Почта России (Russia)', 'Почта России'), ('СДЭК (Russia)', 'СДЭК'), ('Сourier (Only for Moscow and Berlin)', 'Сourier'), ('DHL (Europe)', 'DHL'), ('UPS (Europe)', 'UPS')], max_length=40, null=True),
        ),
    ]
