# Generated by Django 5.1.6 on 2025-03-21 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartZamovApp', '0027_alter_order_delivery_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(blank=True, choices=[('Почта России (Россия)', 'Почта России (Россия)'), ('СДЭК (Россия)', 'СДЭК (Россия)'), ('Сourier (Only for Moscow and Berlin)', 'Сourier (Only for Moscow and Berlin)'), ('DHL (Europe)', 'DHL (Europe)'), ('UPS (Europe)', 'UPS (Europe)')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Cash on delivery', 'Cash on delivery'), ('On card', 'On card'), ('Crypto', 'Crypto')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('On cart', 'On cart'), ('Pending', 'Pending'), ('Completed', 'Completed'), ('Active', 'Active'), ('Shipped', 'Shipped'), ('Canceled', 'Canceled')], default='on_cart', max_length=40),
        ),
    ]
