# Generated by Django 5.1.6 on 2025-03-21 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartZamovApp', '0028_alter_order_delivery_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
