# Generated by Django 5.1.7 on 2025-03-27 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartZamovApp', '0030_tag_product_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='average_price_in_stores',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=13),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='average_price_in_stores_de',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='average_price_in_stores_en',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='average_price_in_stores_ru',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
    ]
