# Generated by Django 5.1.7 on 2025-03-27 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SmartZamovApp', '0031_product_average_price_in_stores_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='average_price_in_stores',
            new_name='price_without_sale',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='average_price_in_stores_de',
            new_name='price_without_sale_de',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='average_price_in_stores_en',
            new_name='price_without_sale_en',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='average_price_in_stores_ru',
            new_name='price_without_sale_ru',
        ),
    ]
