# Generated by Django 5.1.7 on 2025-03-27 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SmartZamovApp', '0034_alter_tag_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='slug',
        ),
    ]
