# Generated by Django 5.1.7 on 2025-03-30 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartZamovApp', '0037_alter_tag_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='due_for_payment_now',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='due_for_payment_now_de',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='due_for_payment_now_en',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='due_for_payment_now_ru',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('On cart', 'On cart'), ('Pending', 'Pending'), ('Waiting_for_payment', 'Waiting_for_payment'), ('Completed', 'Completed'), ('Active', 'Active'), ('Shipped', 'Shipped'), ('Canceled', 'Canceled')], default='on_cart', max_length=40),
        ),
    ]
