# Generated by Django 5.1.7 on 2025-04-12 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartZamovApp', '0039_bankcards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankcards',
            name='card_number',
            field=models.CharField(max_length=16),
        ),
    ]
